/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todoapp;

import controllers.ProjectController;
import controllers.TaskController;
import java.sql.Connection;
import java.util.Date;
import java.util.List;
import models.Project;
import models.Task;
import org.w3c.dom.traversal.DocumentTraversal;
import util.ConnectionFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
                
//        ProjectController contraladorProjetos = new ProjectController();
//        
//        Project projeto = new Project(1, "Primeiro Projeto", "testando controlador", new Date(), new Date());
//        contraladorProjetos.save(projeto);

//        contraladorProjetos.removeById(1);
//        
//        Project novo = new Project();
//        novo.setId(2);
//        novo.setName("Projeto Atualizado");
//        novo.setDescription("Testando update do controller");
//        contraladorProjetos.update(novo);
//        
//        List<Project> projects = contraladorProjetos.getAll();
//        System.out.println(projects.size());

//        TaskController controladorTarefas = new TaskController();
//        
//        Task tarefa = new Task(1, 2, "Primeiro Projeto", "testando controlador", 
//                "obs", false, new Date(), new Date(), new Date());
//        controladorTarefas.save(tarefa);
        
//        controladorTarefas.removeById(1);
//        
//        Task novo = new Task();
//        novo.setId(1);
//        novo.setIdProject(2);
//        novo.setName("tarefa Atualizada");
//        novo.setDescription("Testando update do controller");
//        novo.setNotes("Notas rnd");
//        novo.setDeadline(new Date());
//
//        controladorTarefas.update(novo);
//        
//        List<Task> tarefas = controladorTarefas.getAll(2);
//        System.out.println(tarefas.size());
    }
}
